//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOSBallet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alongamento
    {
        public int IDAlongamento { get; set; }
        public Nullable<int> Nivel { get; set; }
        public string NomeExercicio { get; set; }
        public string DescExercicio { get; set; }
    }
}
