//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOSBallet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SOSBalletBDEntities : DbContext
    {
        public SOSBalletBDEntities()
            : base("name=SOSBalletBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<Alongamento> Alongamento { get; set; }
        public virtual DbSet<Bailarino> Bailarino { get; set; }
        public virtual DbSet<ControleUso> ControleUso { get; set; }
        public virtual DbSet<Materia> Materia { get; set; }
        public virtual DbSet<PontuacaoSimulado> PontuacaoSimulado { get; set; }
        public virtual DbSet<Quiz> Quiz { get; set; }
        public virtual DbSet<Sapatilha> Sapatilha { get; set; }
        public virtual DbSet<Simulado> Simulado { get; set; }
    }
}
