//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOSBallet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PontuacaoSimulado
    {
        public int IDPontuacao { get; set; }
        public Nullable<int> Potuacao { get; set; }
        public Nullable<int> IDBailarino { get; set; }
    
        public virtual Bailarino Bailarino { get; set; }
    }
}
