//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOSBallet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        public int IDQuiz { get; set; }
        public string TipoPe { get; set; }
        public string LarguraPe { get; set; }
        public string TempoNasPontas { get; set; }
        public string DuracaoAnterior { get; set; }
        public string ColoPe { get; set; }
        public Nullable<int> Tamanho { get; set; }
        public Nullable<int> IDSapatilha { get; set; }
    
        public virtual Sapatilha Sapatilha { get; set; }
    }
}
