//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOSBallet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sapatilha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sapatilha()
        {
            this.Quiz = new HashSet<Quiz>();
        }
    
        public int IDSapatilha { get; set; }
        public string Descricao { get; set; }
        public string TipoPe { get; set; }
        public string LarguraPe { get; set; }
        public string TempoNasPontas { get; set; }
        public string DuracaoAnterior { get; set; }
        public string ColoPe { get; set; }
        public Nullable<int> Tamanho { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quiz> Quiz { get; set; }
    }
}
