//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOSBallet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Simulado
    {
        public int IDSimulado { get; set; }
        public string Pergunta { get; set; }
        public string Resposta { get; set; }
        public Nullable<int> IDMateria { get; set; }
    
        public virtual Materia Materia { get; set; }
    }
}
